name: 'CI'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  example:
    name: Example
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install

      - name: Run example
        run: echo Hello, world!